### ISSUE TITLE
release

### ISSUE THREAD

**Issue by glehmann** [simleb/clinfo#2]
Hi,

I'd like to create a package of clinfo for mac, but I would need a released package for that.
I there a chance that you make a release in the near future?

Thanks

**Comment by Oblomov** [comment]
I've just updated the version number (and tagged, and retroactively tagged all past versions), so feel free to proceed. If there's anything specific that needs to be done further for a Mac package, don't hesitate to let me know.

**Comment by simleb** [comment]
Here you go: https://github.com/simleb/clinfo/releases/tag/v1.0
